export const seedTeams = [
  { name: "Varcelona", initial_budget: 100 },
  { name: "Hala Barca", initial_budget: 100 },
  { name: "Thenga FC", initial_budget: 100 },
  { name: "Team Morph", initial_budget: 100 },
  { name: "Padayapas", initial_budget: 100 },
  { name: "Madridistas", initial_budget: 100 },
  { name: "Real United FC", initial_budget: 100 },
];

export const seedPlayers = [
  { enum_name: "MBAPPE", display_name: "Mbappé", position: "ATT" as const, ovr: 91, base_price: 25 },
  { enum_name: "SALAH", display_name: "Salah", position: "ATT" as const, ovr: 91, base_price: 24 },
  { enum_name: "DEMBELE", display_name: "Dembélé", position: "ATT" as const, ovr: 90, base_price: 22 },
  { enum_name: "HAALAND", display_name: "Haaland", position: "ATT" as const, ovr: 90, base_price: 22 },
  { enum_name: "KANE", display_name: "Kane", position: "ATT" as const, ovr: 89, base_price: 20 },
  { enum_name: "VINI_JR", display_name: "Vini Jr.", position: "ATT" as const, ovr: 89, base_price: 20 },
  { enum_name: "LAMINE_YAMAL", display_name: "Lamine Yamal", position: "ATT" as const, ovr: 89, base_price: 19 },
  { enum_name: "RAPHINHA", display_name: "Raphinha", position: "ATT" as const, ovr: 89, base_price: 18 },
  { enum_name: "SAKA", display_name: "Saka", position: "ATT" as const, ovr: 88, base_price: 17 },
  { enum_name: "PALMER", display_name: "Palmer", position: "ATT" as const, ovr: 87, base_price: 16 },
  { enum_name: "ALVAREZ", display_name: "Álvarez", position: "ATT" as const, ovr: 87, base_price: 16 },
  { enum_name: "KVARATSKHELIA", display_name: "Kvaratskhelia", position: "ATT" as const, ovr: 87, base_price: 15 },
  { enum_name: "BENZEMA", display_name: "Benzema", position: "ATT" as const, ovr: 85, base_price: 12 },
  { enum_name: "RODRYGO", display_name: "Rodrygo", position: "ATT" as const, ovr: 85, base_price: 12 },
  { enum_name: "SON", display_name: "Son", position: "ATT" as const, ovr: 85, base_price: 12 },
  { enum_name: "DOUE", display_name: "Doué", position: "ATT" as const, ovr: 85, base_price: 11 },
  { enum_name: "GRIEZMANN", display_name: "Griezmann", position: "ATT" as const, ovr: 85, base_price: 11 },
  { enum_name: "RAFAEL_LEAO", display_name: "Rafael Leão", position: "ATT" as const, ovr: 84, base_price: 10 },
  { enum_name: "ANTONY", display_name: "Antony", position: "ATT" as const, ovr: 81, base_price: 4 },
  { enum_name: "CHERKI", display_name: "Cherki", position: "ATT" as const, ovr: 81, base_price: 4 },
  { enum_name: "RASHFORD", display_name: "Rashford", position: "ATT" as const, ovr: 80, base_price: 2 },
  { enum_name: "BELLINGHAM", display_name: "Bellingham", position: "MID" as const, ovr: 90, base_price: 23 },
  { enum_name: "RODRI", display_name: "Rodri", position: "MID" as const, ovr: 90, base_price: 22 },
  { enum_name: "VITINHA", display_name: "Vitinha", position: "MID" as const, ovr: 89, base_price: 19 },
  { enum_name: "PEDRI", display_name: "Pedri", position: "MID" as const, ovr: 89, base_price: 19 },
  { enum_name: "VALVERDE", display_name: "Valverde", position: "MID" as const, ovr: 89, base_price: 18 },
  { enum_name: "MUSIALA", display_name: "Musiala", position: "MID" as const, ovr: 88, base_price: 17 },
  { enum_name: "DE_BRUYNE", display_name: "De Bruyne", position: "MID" as const, ovr: 87, base_price: 16 },
  { enum_name: "RICE", display_name: "Rice", position: "MID" as const, ovr: 87, base_price: 15 },
  { enum_name: "BRUNO_FERNANDES", display_name: "Bruno Fernandes", position: "MID" as const, ovr: 87, base_price: 15 },
  { enum_name: "ODEGAARD", display_name: "Odegaard", position: "MID" as const, ovr: 87, base_price: 15 },
  { enum_name: "FODEN", display_name: "Foden", position: "MID" as const, ovr: 85, base_price: 13 },
  { enum_name: "DE_PAUL", display_name: "De Paul", position: "MID" as const, ovr: 84, base_price: 10 },
  { enum_name: "BERNARDO_SILVA", display_name: "Bernardo Silva", position: "MID" as const, ovr: 84, base_price: 10 },
  { enum_name: "GAVI", display_name: "Gavi", position: "MID" as const, ovr: 83, base_price: 8 },
  { enum_name: "MODRIC", display_name: "Modrić", position: "MID" as const, ovr: 83, base_price: 8 },
  { enum_name: "BRAHIM", display_name: "Brahim", position: "MID" as const, ovr: 82, base_price: 6 },
  { enum_name: "FERMIN", display_name: "Fermín", position: "MID" as const, ovr: 80, base_price: 2 },
  { enum_name: "CASEMIRO", display_name: "Casemiro", position: "MID" as const, ovr: 80, base_price: 2 },
  { enum_name: "VAN_DIJK", display_name: "van Dijk", position: "DEF" as const, ovr: 90, base_price: 22 },
  { enum_name: "HAKIMI", display_name: "Hakimi", position: "DEF" as const, ovr: 89, base_price: 20 },
  { enum_name: "KIMMICH", display_name: "Kimmich", position: "DEF" as const, ovr: 89, base_price: 19 },
  { enum_name: "GABRIEL", display_name: "Gabriel", position: "DEF" as const, ovr: 88, base_price: 17 },
  { enum_name: "MARQUINHOS", display_name: "Marquinhos", position: "DEF" as const, ovr: 87, base_price: 15 },
  { enum_name: "BASTONI", display_name: "Bastoni", position: "DEF" as const, ovr: 87, base_price: 15 },
  { enum_name: "RUBEN_DIAS", display_name: "Ruben Dias", position: "DEF" as const, ovr: 86, base_price: 14 },
  { enum_name: "NUNO_MENDES", display_name: "Nuno Mendes", position: "DEF" as const, ovr: 86, base_price: 13 },
  { enum_name: "RUDIGER", display_name: "Rüdiger", position: "DEF" as const, ovr: 86, base_price: 13 },
  { enum_name: "ALEXANDER_ARNOLD", display_name: "Alexander-Arnold", position: "DEF" as const, ovr: 86, base_price: 13 },
  { enum_name: "PACHO", display_name: "Pacho", position: "DEF" as const, ovr: 86, base_price: 12 },
  { enum_name: "GVARDIOL", display_name: "Gvardiol", position: "DEF" as const, ovr: 84, base_price: 10 },
  { enum_name: "BALDE", display_name: "Balde", position: "DEF" as const, ovr: 83, base_price: 8 },
  { enum_name: "ARAUJO", display_name: "Araujo", position: "DEF" as const, ovr: 83, base_price: 8 },
  { enum_name: "STONES", display_name: "Stones", position: "DEF" as const, ovr: 82, base_price: 6 },
  { enum_name: "HUIJSEN", display_name: "Huijsen", position: "DEF" as const, ovr: 82, base_price: 6 },
  { enum_name: "DONNARUMMA", display_name: "Donnarumma", position: "GK" as const, ovr: 89, base_price: 19 },
  { enum_name: "COURTOIS", display_name: "Courtois", position: "GK" as const, ovr: 89, base_price: 19 },
  { enum_name: "ALISSON", display_name: "Alisson", position: "GK" as const, ovr: 89, base_price: 18 },
  { enum_name: "OBLAK", display_name: "Oblak", position: "GK" as const, ovr: 88, base_price: 16 },
  { enum_name: "DAVID_RAYA", display_name: "David Raya", position: "GK" as const, ovr: 87, base_price: 14 },
  { enum_name: "TER_STEGEN", display_name: "ter Stegen", position: "GK" as const, ovr: 86, base_price: 13 },
  { enum_name: "MARTINEZ", display_name: "Martínez", position: "GK" as const, ovr: 85, base_price: 11 },
  { enum_name: "DE_GEA", display_name: "De Gea", position: "GK" as const, ovr: 85, base_price: 10 },
  { enum_name: "DIOGO_COSTA", display_name: "Diogo Costa", position: "GK" as const, ovr: 84, base_price: 9 },
  { enum_name: "ONANA", display_name: "Onana", position: "GK" as const, ovr: 80, base_price: 2 },
];
